language: python
job:
  include:
    #- python: "3.8"
    #  env: TOXENV=py38
    #- python: "3.9"
    #  env: TOXENV=py39
    - python: "3.10"
      dist: focal
      env: TOXENV=py310
    - python: "3.11"
      dist: bionic
      env: TOXENV=py311
    - python: "3.10"
      dist: focal
      env: TOXENV=coverage
    - python: "3.10"
      dist: focal
      env: TOXENV=docs
os:
  - linux
git:
  quiet: true
stages:
  - name: install_develop_requirements
    if: branch = develop
    before_install:
    - git clone git@github.com:highcharts-for-python/highcharts-core.git
    - cd highcharts-core
    - git checkout develop
    - pip install -e .
    - cd ../
    - pip install esprima==4.0.1
    - pip install pytest==7.1.2
    - pip install pytest-cov==3.0.0
    - pip install pytest-xdist==2.5.0
    - pip install python-dotenv>=0.20.0
    - pip install pytz==2022.1
    - pip install Sphinx==6.1.3
    - pip install sphinx-rtd-theme==1.2.0
    - pip install sphinx-toolbox==3.4.0
    - pip install sphinx-tabs==3.4.1
    - pip install tox==4.4.6
    - pip install requests==2.28.1
    - pip install urllib3==1.26.9
    - pip install validator-collection==1.5.0
  - name: install_release_requirements
    if: branch = master
    install:
      - pip install -r requirements.dev.txt
  - name: run_tests
    before_script:
    - curl -Os --retry 5 https://uploader.codecov.io/latest/linux/codecov
    - chmod +x codecov
    script: tox -- -v -nauto 
    after_success:
    - if [[ -e .coverage ]]; then ./codecov -t $CODECOV_TOKEN; fi